#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)
SECRET_KEYS=()    # keys captured with hidden input
GITHUB_REPO="${GITHUB_REPO:-}"
_GITHUB_REPO_CHECKED=0
_GITHUB_REPO_READY=0
unset _GITHUB_REPO_CONFIRMED # Internal state, never an inherited target.

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# Shared variable-name validation for prompts, local writes, and GitHub writes.
_valid_name() {
  [[ "$1" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || { warn "invalid variable name"; return 1; }
}

_existing() {
  _valid_name "$1" || return 1
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  _valid_name "$key" || return 1
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  _valid_name "$key" || return 1
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
  SECRET_KEYS+=("$key")
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" secret_key
  _valid_name "$key" || return 1
  if [[ "$value" == *$'\n'* || "$value" == *$'\x0d'* ]]; then
    warn "refusing multiline value for $key"
    return 1
  fi
  for secret_key in "${SECRET_KEYS[@]}"; do
    if [[ "$key" == "$secret_key" ]]; then
      command -v git >/dev/null 2>&1 || { warn "cannot verify secret destination without Git"; return 1; }
      (
        cd -- "$(dirname -- "$ENV_FILE")" || return 1
        if [[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" == true ]]; then
          git check-ignore -- "$(basename -- "$ENV_FILE")" >/dev/null 2>&1 || {
            warn "refusing secret write: $ENV_FILE must be ignored and untracked"
            return 1
          }
        fi
      ) || return 1
    fi
  done
  (
    local tmp status
    tmp=$(mktemp "${ENV_FILE}.XXXXXX") || return 1
    trap 'rm -f -- "$tmp"' EXIT
    trap 'exit 1' HUP INT TERM
    if [[ -e "$ENV_FILE" ]]; then
      if grep -vE "^${key}=" "$ENV_FILE" > "$tmp"; then
        :
      else
        status=$?
        [[ "$status" == 1 ]] || return "$status"
      fi
      # Preserve the separator when the old file has no final newline.
      if [[ -s "$tmp" && -n "$(tail -c 1 "$tmp")" ]]; then
        printf '\n' >> "$tmp" || return 1
      fi
    fi
    printf '%s=%s\n' "$key" "$value" >> "$tmp" || return 1
    mv -- "$tmp" "$ENV_FILE" || return 1
  ) || { warn "could not write $key; original $ENV_FILE preserved"; return 1; }
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# Resolve once, confirm before any remote write, and reuse the exact target.
_github_repo() {
  if (( _GITHUB_REPO_CHECKED )); then
    (( _GITHUB_REPO_READY ))
    return
  fi
  _GITHUB_REPO_CHECKED=1
  command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 || return 1
  if [[ -z "$GITHUB_REPO" ]]; then
    GITHUB_REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner) || return 1
  fi
  [[ "$GITHUB_REPO" =~ ^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$ ]] || return 1
  confirm "Write GitHub secrets/variables to $GITHUB_REPO?" || return 1
  if [[ ! -v _GITHUB_REPO_CONFIRMED ]]; then
    readonly _GITHUB_REPO_CONFIRMED="$GITHUB_REPO"
  fi
  _GITHUB_REPO_READY=1
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  _valid_name "$name" || return 1
  if _github_repo; then
    if printf '%s' "$value" | gh secret set "$name" --repo "$_GITHUB_REPO_CONFIRMED" >/dev/null 2>&1 &&
      gh secret list --repo "$_GITHUB_REPO_CONFIRMED" --json name --jq '.[].name' | grep -Fx -- "$name" >/dev/null; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (target ${_GITHUB_REPO_CONFIRMED:-${GITHUB_REPO:-unresolved}}; write or name verification incomplete)")
  warn "GitHub secret $name incomplete; check the confirmed repository manually"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2" actual
  _valid_name "$name" || return 1
  if _github_repo; then
    if gh variable set "$name" --body "$value" --repo "$_GITHUB_REPO_CONFIRMED" >/dev/null 2>&1 &&
      actual=$(gh variable get "$name" --repo "$_GITHUB_REPO_CONFIRMED" --json value --jq .value) &&
      [[ "$actual" == "$value" ]]; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "GitHub variable $name incomplete; check the confirmed repository manually"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe: API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
